### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by AshM10** [marktnoonan/transcription#51]
I tried using this for class. Although it works, when the professor speaks fast, it won't get all the words.

**Comment by marktnoonan** [comment]
Thanks @AshM10 for reporting the issue! This project has been a bit neglected for the last few years. Sorry it didn't do a good job picking up your professor, there's not much we can do about that though, since it's built on the speech recognition provided by the browser. There's nothing we can change in the code to make that better or worse, the only thing I can think of is to get closer to the professor, higher quality audio, etc.

**Comment by AshM10** [comment]
Thank you! It's still a big help!
